CREATE_CUSTOMERS_SQL = "CREATE TABLE CUSTOMERS (     ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),     EMAIL VARCHAR(256) NOT NULL UNIQUE,     PASSWORD VARCHAR(256) NOT NULL,     FIRST_NAME VARCHAR(256) NOT NULL,     LAST_NAME VARCHAR(256) NOT NULL,     MOBILE VARCHAR(45) NOT NULL UNIQUE,     GENDER VARCHAR(45) NOT NULL,     ADDRESS VARCHAR(256) NOT NULL,     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,     PRIMARY KEY(ID)      )"

CREATE_AGENTS_SQL = "CREATE TABLE AGENTS (     ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),     EMAIL VARCHAR(256) NOT NULL UNIQUE,     PASSWORD VARCHAR(256) NOT NULL,     FIRST_NAME VARCHAR(256) NOT NULL,     LAST_NAME VARCHAR(256) NOT NULL,     CATEGORY VARCHAR(64) NOT NULL,     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,     PRIMARY KEY(ID)      );"


CREATE_ADMINS_SQL = "CREATE TABLE ADMINS (     ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),     EMAIL VARCHAR(256) NOT NULL UNIQUE,     PASSWORD VARCHAR(256) NOT NULL,     FIRST_NAME VARCHAR(256) NOT NULL,     LAST_NAME VARCHAR(256) NOT NULL,     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,     PRIMARY KEY(ID)   );"

CREATE_COMPLAINTS_SQL = "CREATE TABLE COMPLAINTS (     ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),     CUSTOMER_ID INT NOT NULL,     TITLE VARCHAR(256) NOT NULL,     CATEGORY VARCHAR(64) NOT NULL,     STATUS VARCHAR(64) NOT NULL,     DESCRIPTION VARCHAR(1024) NOT NULL,     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,     PRIMARY KEY(ID),     FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON UPDATE NO ACTION ON DELETE CASCADE      );"

CREATE_STATUS_SQL = "CREATE TABLE STATUS (     ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),     TITLE VARCHAR(256) NOT NULL,     PRIMARY KEY(ID)   );"

CREATE_COMPLAINT_STATUS_ASSIGN = "CREATE TABLE   COMPLAINT_ASSIGN_STATUS (     ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (       START       WITH         1 INCREMENT BY 1     ),     COMPLAINT_ID INT NOT NULL,     STATUS VARCHAR(64) NOT NULL,     AGENT_ID INT NOT NULL,     PRIMARY KEY(ID),     FOREIGN KEY(COMPLAINT_ID) REFERENCES COMPLAINTS(ID) ON UPDATE NO ACTION ON DELETE CASCADE,     FOREIGN KEY(AGENT_ID) REFERENCES AGENTS(ID) ON UPDATE NO ACTION ON DELETE CASCADE,     UNIQUE(COMPLAINT_ID,AGENT_ID)      );"

